### ISSUE TITLE
Launcher Don't Open

### ISSUE THREAD

**Issue by brenoferreiralima** [flathub/com.albiononline.AlbionOnline#38]
flatpak run com.albiononline.AlbionOnline    
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1406, in connect
    super().connect()
  File "/usr/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/app/bin/get_albion_online_download_uri", line 10, in <module>
    manifest = urlopen(manifest_uri)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
Gtk-Message: 13:43:23.696: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:43:23.696: Failed to load module "pk-gtk-module"
Gtk-Message: 13:43:23.696: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:43:23.696: Failed to load module "pk-gtk-module"
splitelf: No such file or directory

OS: Fedora Workstation 33
Flatpak: 1.10.1

**Comment by brenoferreiralima** [comment]
was a problem with my dns and the game servers...
